services:

  backend:
    image: markoveni/task-manager:backend-2e3a7e32
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - ALLOWED_ORIGINS=http://127.0.0.1:8080|http://localhost:8080
    volumes:
      - ../task-manager/backend/taskmanager.db:/app/taskmanager.db
  frontend:
    image: markoveni/task-manager:frontend-2e3a7e32
    ports:
      - 127.0.0.1:8080:8080

volumes:
  backend_db:
