services:

  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - ${SQLITE_DB_PATH}:/app/taskmanager.db # bind mount
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - 127.0.0.1:8080:8080

volumes:
  backend_db:
