name: tmp

on:
    workflow_call:

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "ci/.python-version"

      - name: Install MkDocs and dependencies
        run: pip install mkdocs

      - name: Generate static files # files are generate under site/ folder
        run: mkdocs build -d site

      - name: Setup pages
        uses: actions/configure-pages@v5

        # Upload to github pages
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site/

      - name: Deploy it to serve it as static file
        id: deployment
        uses: actions/deploy-pages@v4

      # Echo the url in order to retrieve the artifact
      - run: echo ${{ steps.deployment.outputs.page_url }}
